
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    # Add environment variables if needed
    # environment:
    #   - VARIABLE_NAME=value
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
